language: java
jdk:
    - oraclejdk7
    - oraclejdk8

install:
    - wget https://github.com/google/protobuf/releases/download/v2.5.0/protobuf-2.5.0.tar.bz2
    - tar -xjvf protobuf-2.5.0.tar.bz2
    - pushd protobuf-2.5.0 && ./configure --prefix=/usr && make && sudo make install && popd
